#Create an environment specific for RNA-seq data preprocessing 
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - defaults
dependencies:
  - FastQC=0.11.9
  - MultiQC=1.9
  - trim-galore=0.6.5
  - samtools=1.11
  - star=2.7.0e
  - featureCounts=2.0.1
  